name: Deploy example to GitHub pages

on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0

      - name: clean cache
        run: npm cache clean --force

      - name: npm install
        run: npm install

      - name: deploy to github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/hubblr/hubblr-react-components
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}